# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet-build-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.x

      - name: Build and publish with dotnet
        working-directory: TailwindTraders.Website/Source/Tailwind.Traders.Web
        run: |
          dotnet build --configuration Release
          dotnet test --configuration Release
          dotnet publish -c Release -o publish
